version: '3.7'

volumes:
  peer0.userlog-org2.example.com:

networks:
  test:
    name: fabric_test

x-common-variables: &common-environment
  FABRIC_CFG_PATH: /etc/hyperledger/peercfg
  FABRIC_LOGGING_SPEC: DEBUG
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "false"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
  CORE_VM_DOCKER_ATTACHSTDOUT: "true"
  CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/fabric/msp
  CORE_METRICS_PROVIDER: prometheus
  CORE_CHAINCODE_EXECUTETIMEOUT: 300s
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: fabric_test
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: admin
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpw

services:
  peer0.userlog-org2.example.com:
    container_name: peer0.userlog-org2.example.com
    image: hyperledger/fabric-peer:2.5.0
    labels:
      service: hyperledger-fabric
    environment:
      <<: *common-environment
      # Peer specific variables
      CORE_PEER_ID: peer0.userlog-org2.example.com
      CORE_PEER_ADDRESS: peer0.userlog-org2.example.com:9051
      CORE_PEER_LISTENADDRESS: 0.0.0.0:9051
      CORE_PEER_CHAINCODEADDRESS: peer0.userlog-org2.example.com:9052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:9052
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.userlog-org2.example.com:9051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.userlog-org2.example.com:9051
      CORE_PEER_LOCALMSPID: Org2MSP
      CORE_OPERATIONS_LISTENADDRESS: peer0.userlog-org2.example.com:9446
      CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG: '{"peername":"peer0userlogorg2"}'
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb-peer0-org2:5984
    volumes:
      - ../organizations/peerOrganizations/userlog-org2.example.com/peers/peer0.userlog-org2.example.com:/etc/hyperledger/fabric
      - peer0.userlog-org2.example.com:/var/hyperledger/production
#      - ../backup/peer0.userlog-org2:/var/hyperledger/production
#      - ../backup/organizations/peerOrganizations/userlog-org2.example.com/peers/peer0.userlog-org2.example.com:/etc/hyperledger/fabric
      #Generic peer variables
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9446:9446
    networks:
      - test
    depends_on:
      - couchdb-peer0-org2
