version: '3.7'

volumes:
  peer0.userlog-org1.example.com:
  peer0.userlog-org2.example.com:
networks:
  test:
    name: fabric_test

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.0
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./docker/peercfg:/etc/hyperledger/peercfg
    depends_on:
      - peer0.userlog-org1.example.com
      - peer0.userlog-org2.example.com
    networks:
      - test
